name: Build zip

on:
  workflow_dispatch

jobs:
  build:
    name: Build zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build plugin
      uses: pnpm/action-setup@v2
      with:
        version: latest
        run_install: true

    - name: Build zip
      uses: 10up/action-wordpress-plugin-build-zip@stable
      env:
        SLUG: environment-debug-admin-toolbar
      with:
        retention-days: 1